CREATE TABLE PESSOA (
    ID SERIAL PRIMARY KEY UNIQUE,
    NOME varchar(100),
    FK_ENDERECO_ID int
);

CREATE TABLE PESSOAFISICA (
    CPF bigint,
    RG int,
    DATANASCIMENTO date,
    FK_PESSOA_ID int PRIMARY KEY,
    FK_NACIONALIDADE_ID int,
    FK_ESTADOCIVIL_ID int,
    FK_SEXO_ID int,
    FK_CIDADE_ID int,
    UNIQUE (CPF, RG, FK_PESSOA_ID)
);

CREATE TABLE OCORRENCIA (
    ID INT PRIMARY KEY UNIQUE,
    DATAOCORRENCIA date,
    DATAREGISTRO date,
    HORAREGISTRO time without time zone,
    HORAOCORRENCIA time without time zone,
    FK_PESSOAFISICA_FK_PESSOA_ID int,
    FK_ENDERECO_ID int,
    FK_DELEGACIA_FK_PESSOA_ID int
);

CREATE TABLE ENDERECO (
    ID SERIAL PRIMARY KEY UNIQUE,
    NOME varchar(70),
    CEP int,
    FK_BAIRRO_ID int,
    FK_LOGRADOURO_ID int
);

CREATE TABLE USUARIO (
    ID SERIAL PRIMARY KEY,
    SENHA varchar(50),
    LOGIN varchar(50),
    FK_PESSOAFISICA_FK_PESSOA_ID int,
    UNIQUE (ID, LOGIN, FK_PESSOAFISICA_FK_PESSOA_ID)
);

CREATE TABLE DELEGACIA (
    CNPJ bigint,
    FK_PESSOA_ID int PRIMARY KEY,
    UNIQUE (CNPJ, FK_PESSOA_ID)
);

CREATE TABLE BAIRRO (
    ID SERIAL PRIMARY KEY UNIQUE,
    NOME varchar(50),
    FK_CIDADE_ID int
);

CREATE TABLE LOGRADOURO (
    ID SERIAL PRIMARY KEY,
    NOME varchar(50),
    UNIQUE (ID, NOME)
);

CREATE TABLE CIDADE (
    ID SERIAL PRIMARY KEY UNIQUE,
    NOME varchar(50),
    FK_ESTADO_ID int
);

CREATE TABLE ESTADO (
    ID SERIAL PRIMARY KEY UNIQUE,
    NOME varchar(50)
);

CREATE TABLE TIPOOCORRENCIA (
    ID SERIAL PRIMARY KEY,
    NOME varchar(50),
    UNIQUE (ID, NOME)
);

CREATE TABLE ESTADOCIVIL (
    ID SERIAL PRIMARY KEY,
    NOME varchar(50),
    UNIQUE (ID, NOME)
);

CREATE TABLE PROFISSAO (
    ID SERIAL PRIMARY KEY,
    NOME varchar(50),
    UNIQUE (ID, NOME)
);

CREATE TABLE NACIONALIDADE (
    ID SERIAL PRIMARY KEY,
    NOME varchar(50),
    UNIQUE (ID, NOME)
);

CREATE TABLE SEXO (
    ID SERIAL PRIMARY KEY,
    NOME varchar(50),
    UNIQUE (ID, NOME)
);


CREATE TABLE CONTATO (
    ID SERIAL PRIMARY KEY,
    DESCRICAO varchar(50),
    FK_PESSOA_ID int,
    FK_TIPOCONTATO_ID int,
    UNIQUE (ID, DESCRICAO)
);

CREATE TABLE TIPOCONTATO (
    ID SERIAL PRIMARY KEY,
    NOME varchar(50),
    UNIQUE (ID, NOME)
);

CREATE TABLE PROFISSAO_PESSOA (
    FK_PROFISSAO_ID int,
    FK_PESSOAFISICA_FK_PESSOA_ID int,
    ID SERIAL PRIMARY KEY UNIQUE
);

CREATE TABLE OCORRENCIA_TIPOOCORRENCIA (
    FK_TIPOOCORRENCIA_ID int,
    FK_OCORRENCIA_ID int,
    ID SERIAL PRIMARY KEY UNIQUE
);
 
ALTER TABLE PESSOAFISICA ADD CONSTRAINT FK_PESSOAFISICA_1
    FOREIGN KEY (FK_PESSOA_ID)
    REFERENCES PESSOA (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PESSOAFISICA ADD CONSTRAINT FK_PESSOAFISICA_2
    FOREIGN KEY (FK_NACIONALIDADE_ID)
    REFERENCES NACIONALIDADE (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PESSOAFISICA ADD CONSTRAINT FK_PESSOAFISICA_3
    FOREIGN KEY (FK_ESTADOCIVIL_ID)
    REFERENCES ESTADOCIVIL (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PESSOAFISICA ADD CONSTRAINT FK_PESSOAFISICA_4
    FOREIGN KEY (FK_SEXO_ID)
    REFERENCES SEXO (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PESSOAFISICA ADD CONSTRAINT FK_PESSOAFISICA_5
    FOREIGN KEY (FK_CIDADE_ID)
    REFERENCES CIDADE (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE OCORRENCIA ADD CONSTRAINT FK_OCORRENCIA_1
    FOREIGN KEY (FK_PESSOAFISICA_FK_PESSOA_ID)
    REFERENCES PESSOAFISICA (FK_PESSOA_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE OCORRENCIA ADD CONSTRAINT FK_OCORRENCIA_2
    FOREIGN KEY (FK_ENDERECO_ID)
    REFERENCES ENDERECO (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE OCORRENCIA ADD CONSTRAINT FK_OCORRENCIA_3
    FOREIGN KEY (FK_DELEGACIA_FK_PESSOA_ID)
    REFERENCES DELEGACIA (FK_PESSOA_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_1
    FOREIGN KEY (FK_BAIRRO_ID)
    REFERENCES BAIRRO (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_2
    FOREIGN KEY (FK_LOGRADOURO_ID)
    REFERENCES LOGRADOURO (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_1
    FOREIGN KEY (FK_PESSOAFISICA_FK_PESSOA_ID)
    REFERENCES PESSOAFISICA (FK_PESSOA_ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE DELEGACIA ADD CONSTRAINT FK_DELEGACIA_1
    FOREIGN KEY (FK_PESSOA_ID)
    REFERENCES PESSOA (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE BAIRRO ADD CONSTRAINT FK_BAIRRO_1
    FOREIGN KEY (FK_CIDADE_ID)
    REFERENCES CIDADE (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_1
    FOREIGN KEY (FK_ESTADO_ID)
    REFERENCES ESTADO (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PESSOA ADD CONSTRAINT FK_PESSOA_1
    FOREIGN KEY (FK_ENDERECO_ID)
    REFERENCES ENDERECO (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_1
    FOREIGN KEY (FK_PESSOA_ID)
    REFERENCES PESSOA (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE CONTATO ADD CONSTRAINT FK_CONTATO_2
    FOREIGN KEY (FK_TIPOCONTATO_ID)
    REFERENCES TIPOCONTATO (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE PROFISSAO_PESSOA ADD CONSTRAINT FK_PROFISSAO_PESSOA_0
    FOREIGN KEY (FK_PROFISSAO_ID)
    REFERENCES PROFISSAO (ID)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE PROFISSAO_PESSOA ADD CONSTRAINT FK_PROFISSAO_PESSOA_1
    FOREIGN KEY (FK_PESSOAFISICA_FK_PESSOA_ID)
    REFERENCES PESSOAFISICA (FK_PESSOA_ID)
    ON DELETE SET NULL ON UPDATE CASCADE;
 
ALTER TABLE OCORRENCIA_TIPOOCORRENCIA ADD CONSTRAINT FK_OCORRENCIA_TIPOOCORRENCIA_0
    FOREIGN KEY (FK_TIPOOCORRENCIA_ID)
    REFERENCES TIPOOCORRENCIA (ID)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE OCORRENCIA_TIPOOCORRENCIA ADD CONSTRAINT FK_OCORRENCIA_TIPOOCORRENCIA_1
    FOREIGN KEY (FK_OCORRENCIA_ID)
    REFERENCES OCORRENCIA (ID)
    ON DELETE SET NULL ON UPDATE CASCADE;